services:
  task-tracker:
    container_name: tasktracker
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=tracker_admin123
      - POSTGRES_DB=tasktracker
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data